/**
 * Banner patterns: which designs there are, what each looks like, and how each
 * era of the game writes them into a block entity.
 *
 * ```
 * resources/banner_patterns.json    the facts, with provenance  <- .claude/skills/mc-banner-patterns
 * scripts/gen-banner-patterns.mjs   JSON -> the table
 * src/shared/banner_patterns.ts     this file
 * ```
 *
 * In `shared/` because three places ask it and only one of them is main: the
 * renderer's block field recognises a banner to show the editor link, the MCP
 * tools describe the designs to a model, and the pipeline reads and writes the
 * NBT (`main/pipeline/banner_nbt.ts`).
 *
 * ## The three spellings, and why they are one table
 *
 * | | a layer | the list | colours |
 * |---|---|---|---|
 * | 1.8 to 1.12.2 | `{Pattern:"moj",Color:14}` | `Patterns`, plus `Base` | `15 - dye` |
 * | 1.13 to 1.20.4 | `{Pattern:"moj",Color:1}` | `Patterns` | the dye's id |
 * | 1.20.5 on | `{pattern:"minecraft:mojang",color:"orange"}` | `patterns` | the dye's name |
 *
 * The boundaries are where the game's own datafixers sit, not where a changelog
 * says something moved: `BlockEntityBannerColorFix` at DataVersion 1451 and
 * `BannerPatternFormatFix` at 3818. The first release on the far side of 3818
 * is 1.20.5; the Flattening is 1.13.
 *
 * Legacy stores the colour inverted *and* keeps the banner's own colour in
 * `Base`, because a pre-Flattening banner is one block for all sixteen colours
 * (`legacy_blocks.json` maps 176 and 177 to `white_banner` and
 * `white_wall_banner`, whatever `Base` says).
 */

import { dataVersionOf } from "./mc_versions.js";

/** One design, as the table records it. */
export interface BannerPatternRow {
  /** `mojang`: the registry id without its namespace, and its texture's name. */
  readonly id: string;
  /**
   * `moj`: what 1.8 to 1.20.4 stored as `Pattern`. `null` for the designs that
   * arrived after that spelling was retired, which is why they cannot be
   * written into an older file at all.
   */
  readonly code: string | null;
  /** The first release the design can be made in, by version name. */
  readonly since: string;
  /** What the game calls it, without the colour: `Thing`, `Chevron`. */
  readonly name: string;
  /** Where it sits on the flag, seen from the front. */
  readonly description: string;
}

// --- generated by scripts/gen-banner-patterns.mjs -- do not edit below -----

export const BANNER_COLORS = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"] as const;

export const INVERTED_COLORS_BEFORE = 1451;
export const NAMED_PATTERNS_FROM = 3818;

export const BANNER_PATTERNS: readonly BannerPatternRow[] = [
  {
    id: "base",
    code: "b",
    since: "JE_1_8_8",
    name: "Field",
    description: "Covers the whole flag. Used as the first layer, it repaints the banner's own colour for everything above it.",
  },
  {
    id: "square_bottom_left",
    code: "bl",
    since: "JE_1_8_8",
    name: "Base Dexter Canton",
    description: "A rectangle in the bottom-left corner: the left half of the bottom third.",
  },
  {
    id: "square_bottom_right",
    code: "br",
    since: "JE_1_8_8",
    name: "Base Sinister Canton",
    description: "A rectangle in the bottom-right corner: the right half of the bottom third.",
  },
  {
    id: "square_top_left",
    code: "tl",
    since: "JE_1_8_8",
    name: "Chief Dexter Canton",
    description: "A rectangle in the top-left corner: the left half of the top third.",
  },
  {
    id: "square_top_right",
    code: "tr",
    since: "JE_1_8_8",
    name: "Chief Sinister Canton",
    description: "A rectangle in the top-right corner: the right half of the top third.",
  },
  {
    id: "stripe_bottom",
    code: "bs",
    since: "JE_1_8_8",
    name: "Base",
    description: "A horizontal band across the bottom third of the flag.",
  },
  {
    id: "stripe_top",
    code: "ts",
    since: "JE_1_8_8",
    name: "Chief",
    description: "A horizontal band across the top third of the flag.",
  },
  {
    id: "stripe_left",
    code: "ls",
    since: "JE_1_8_8",
    name: "Pale Dexter",
    description: "A vertical band down the left third of the flag.",
  },
  {
    id: "stripe_right",
    code: "rs",
    since: "JE_1_8_8",
    name: "Pale Sinister",
    description: "A vertical band down the right third of the flag.",
  },
  {
    id: "stripe_center",
    code: "cs",
    since: "JE_1_8_8",
    name: "Pale",
    description: "A vertical band down the middle of the flag, about a third of its width.",
  },
  {
    id: "stripe_middle",
    code: "ms",
    since: "JE_1_8_8",
    name: "Fess",
    description: "A narrow horizontal band across the middle of the flag, about a fifth of its height.",
  },
  {
    id: "stripe_downright",
    code: "drs",
    since: "JE_1_8_8",
    name: "Bend",
    description: "A diagonal band from the top-left corner down to the bottom-right corner.",
  },
  {
    id: "stripe_downleft",
    code: "dls",
    since: "JE_1_8_8",
    name: "Bend Sinister",
    description: "A diagonal band from the top-right corner down to the bottom-left corner.",
  },
  {
    id: "small_stripes",
    code: "ss",
    since: "JE_1_8_8",
    name: "Paly",
    description: "Four thin vertical stripes running the full height of the flag, evenly spaced.",
  },
  {
    id: "cross",
    code: "cr",
    since: "JE_1_8_8",
    name: "Saltire",
    description: "A diagonal cross: two bands from corner to corner, meeting in the centre like an X.",
  },
  {
    id: "straight_cross",
    code: "sc",
    since: "JE_1_8_8",
    name: "Cross",
    description: "An upright cross: a vertical band down the middle and a horizontal band across the middle.",
  },
  {
    id: "triangle_bottom",
    code: "bt",
    since: "JE_1_8_8",
    name: "Chevron",
    description: "A triangle standing on the whole bottom edge, rising to a point at the centre of the flag.",
  },
  {
    id: "triangle_top",
    code: "tt",
    since: "JE_1_8_8",
    name: "Inverted Chevron",
    description: "A triangle hanging from the whole top edge, down to a point at the centre of the flag.",
  },
  {
    id: "triangles_bottom",
    code: "bts",
    since: "JE_1_8_8",
    name: "Base Indented",
    description: "Three small saw-teeth standing along the bottom edge.",
  },
  {
    id: "triangles_top",
    code: "tts",
    since: "JE_1_8_8",
    name: "Chief Indented",
    description: "Three small saw-teeth hanging along the top edge.",
  },
  {
    id: "diagonal_left",
    code: "ld",
    since: "JE_1_8_8",
    name: "Per Bend Sinister",
    description: "The top-left half of the flag, above the diagonal from the bottom-left corner to the top-right corner.",
  },
  {
    id: "diagonal_up_right",
    code: "rd",
    since: "JE_1_8_8",
    name: "Per Bend Sinister Inverted",
    description: "The bottom-right half of the flag, below the diagonal from the bottom-left corner to the top-right corner.",
  },
  {
    id: "diagonal_up_left",
    code: "lud",
    since: "JE_1_8_8",
    name: "Per Bend Inverted",
    description: "The bottom-left half of the flag, below the diagonal from the top-left corner to the bottom-right corner.",
  },
  {
    id: "diagonal_right",
    code: "rud",
    since: "JE_1_8_8",
    name: "Per Bend",
    description: "The top-right half of the flag, above the diagonal from the top-left corner to the bottom-right corner.",
  },
  {
    id: "circle",
    code: "mc",
    since: "JE_1_8_8",
    name: "Roundel",
    description: "A disc in the centre of the flag.",
  },
  {
    id: "rhombus",
    code: "mr",
    since: "JE_1_8_8",
    name: "Lozenge",
    description: "A large diamond in the centre of the flag, about three fifths of its width and height.",
  },
  {
    id: "half_vertical",
    code: "vh",
    since: "JE_1_8_8",
    name: "Per Pale",
    description: "The left half of the flag.",
  },
  {
    id: "half_horizontal",
    code: "hh",
    since: "JE_1_8_8",
    name: "Per Fess",
    description: "The top half of the flag.",
  },
  {
    id: "half_vertical_right",
    code: "vhr",
    since: "JE_1_8_8",
    name: "Per Pale Inverted",
    description: "The right half of the flag.",
  },
  {
    id: "half_horizontal_bottom",
    code: "hhb",
    since: "JE_1_8_8",
    name: "Per Fess Inverted",
    description: "The bottom half of the flag.",
  },
  {
    id: "border",
    code: "bo",
    since: "JE_1_8_8",
    name: "Bordure",
    description: "A straight frame around all four edges of the flag.",
  },
  {
    id: "curly_border",
    code: "cbo",
    since: "JE_1_8_8",
    name: "Bordure Indented",
    description: "A frame around all four edges whose inner edge is scalloped into rounded notches.",
  },
  {
    id: "gradient",
    code: "gra",
    since: "JE_1_8_8",
    name: "Gradient",
    description: "The colour is solid at the top and fades out towards the bottom, where what is underneath shows through.",
  },
  {
    id: "gradient_up",
    code: "gru",
    since: "JE_1_8_8",
    name: "Base Gradient",
    description: "The colour is solid at the bottom and fades out towards the top, where what is underneath shows through.",
  },
  {
    id: "bricks",
    code: "bri",
    since: "JE_1_8_8",
    name: "Field Masoned",
    description: "Brickwork over the whole flag: the bricks take the colour, and the thin mortar lines between them show what is underneath.",
  },
  {
    id: "globe",
    code: "glb",
    since: "JE_1_14",
    name: "Globe",
    description: "A small globe, in the middle of the flag.",
  },
  {
    id: "creeper",
    code: "cre",
    since: "JE_1_8_8",
    name: "Creeper Charge",
    description: "A creeper's face in the middle of the flag.",
  },
  {
    id: "skull",
    code: "sku",
    since: "JE_1_8_8",
    name: "Skull Charge",
    description: "A skull over crossed bones, in the middle of the flag.",
  },
  {
    id: "flower",
    code: "flo",
    since: "JE_1_8_8",
    name: "Flower Charge",
    description: "A round flower with eight petals, in the middle of the flag.",
  },
  {
    id: "mojang",
    code: "moj",
    since: "JE_1_8_8",
    name: "Thing",
    description: "The Mojang logo, in the middle of the flag.",
  },
  {
    id: "piglin",
    code: "pig",
    since: "JE_1_16",
    name: "Snout",
    description: "A piglin's snout with its two nostrils, in the middle of the flag.",
  },
  {
    id: "flow",
    code: null,
    since: "JE_1_21",
    name: "Flow",
    description: "A squared-off spiral, in the middle of the flag.",
  },
  {
    id: "guster",
    code: null,
    since: "JE_1_21",
    name: "Guster",
    description: "A breeze, the wind mob of trial chambers, in the middle of the flag.",
  },
];

// --- end generated ---------------------------------------------------------

/** A dye's name, in the order every pre-1.20.5 file numbers them. */
export type DyeName = (typeof BANNER_COLORS)[number];

/**
 * Vanilla's `DyeColor.textureDiffuseColor`, which is what the base layer is
 * multiplied by -- the cloth, every layer, and the swatches in the inspector.
 *
 * Corroborated against the pack rather than trusted: every one of the sixteen
 * is within 35 of the mean of its own `<colour>_wool` texture, and every one
 * of those means is the same hue a shade darker -- which is what a wool
 * texture is. A transposed pair would show up as two colours swapping places,
 * not as a uniform offset.
 */
export const DYE_HEX: Readonly<Record<DyeName, string>> = {
  white: "f9fffe",
  orange: "f9801d",
  magenta: "c74ebd",
  light_blue: "3ab3da",
  yellow: "fed83d",
  lime: "80c71f",
  pink: "f38baa",
  gray: "474f52",
  light_gray: "9d9d97",
  cyan: "169c9c",
  purple: "8932b8",
  blue: "3c44aa",
  brown: "835432",
  green: "5e7c16",
  red: "b02e26",
  black: "1d1d21",
};

/**
 * How many layers the game draws. `BannerRenderer` stops at sixteen, and 1.8.8
 * began limiting commands to the same number, so a seventeenth is refused
 * rather than written into a file where it would never be seen.
 */
export const MAX_BANNER_LAYERS = 16;

/** What a loom lets a player make. More is legal and needs commands. */
export const LOOM_LAYER_LIMIT = 6;

/**
 * Where a person designs a banner and gets the `/give` command this app reads.
 *
 * One constant, because two places show it -- the block field and the creative
 * inventory -- and the MCP tools name it to a model that may be talking to
 * somebody without the app in front of them.
 */
export const BANNER_EDITOR_URL = "https://www.planetminecraft.com/banner/";

/** Which of the three spellings a document uses. */
export type BannerFormat = "legacy" | "coded" | "named";

export function bannerFormat(era: "legacy" | "flat", dataVersion: number | null): BannerFormat {
  if (era === "legacy") return "legacy";
  // No number on a flat document means nobody said, and the newest spelling is
  // what a file written today should carry.
  if (dataVersion !== null && dataVersion < NAMED_PATTERNS_FROM) return "coded";
  return "named";
}

const BY_ID = new Map(BANNER_PATTERNS.map((row) => [row.id, row]));
const BY_CODE = new Map(
  BANNER_PATTERNS.filter((row) => row.code !== null).map((row) => [row.code as string, row]),
);

/**
 * A design by any of the names a file or a person uses for it: `mojang`,
 * `minecraft:mojang`, or the old code `moj`.
 *
 * Ids and codes never collide -- every code is three letters or fewer and no id
 * is -- so one lookup serves both without having to be told which spelling it
 * was handed.
 */
export function bannerPattern(text: string): BannerPatternRow | null {
  const bare = text.trim().replace(/^minecraft:/, "");
  return BY_ID.get(bare) ?? BY_CODE.get(bare) ?? null;
}

/** The dye's number in the modern order, or `null` for a name that is not a dye. */
export function dyeIndex(name: string): number | null {
  const index = (BANNER_COLORS as readonly string[]).indexOf(name.trim().replace(/^minecraft:/, ""));
  return index === -1 ? null : index;
}

/** `magenta_banner` and `magenta_wall_banner`, and nothing that merely mentions banners. */
export function isBannerBlock(namespacedName: string): boolean {
  return /_(?:wall_)?banner$/.test(namespacedName.replace(/^[^:]*:/, ""));
}

/** The colour a banner block's name gives it, or `null` if it names none. */
export function bannerBlockColor(namespacedName: string): DyeName | null {
  const colour = namespacedName.replace(/^[^:]*:/, "").replace(/_(?:wall_)?banner$/, "");
  return dyeIndex(colour) === null ? null : (colour as DyeName);
}

/**
 * Whether a design exists in the version a document is for.
 *
 * A flat document with no DataVersion is taken to be current, for
 * `bannerFormat`'s reason. A legacy one with none is 1.8.8, which has only the
 * designs banners shipped with.
 */
export function patternExistsIn(
  row: BannerPatternRow,
  era: "legacy" | "flat",
  dataVersion: number | null,
): boolean {
  const since = dataVersionOf(row.since);
  if (since === null) return true;
  if (dataVersion === null) return era === "flat";
  return dataVersion >= since;
}
