/**
 * The commands this app writes into a `.mcfunction`, and the limits that decide
 * how it writes them.
 *
 * In `shared/` for `mc_versions.ts`'s reason: the export dialog has to say what
 * a file will be runnable on, and main has to write inside the same limits.
 *
 * ## Two kinds of fact, held to two standards
 *
 * The **syntax** is mechanically detectable. The writer emits it, the reader
 * parses it back, and `tests/formats.ts` fails if the two disagree -- so one
 * source is enough, exactly as for `mc-blockstates`. A wrong answer cannot
 * survive a round trip.
 *
 * The **limits** cannot fail here at all. A function past
 * `max_command_sequence_length` is truncated by the game with no error, and a
 * `fill` past `max_block_modifications` places nothing and reports success.
 * Neither is visible from inside this repo, ever, which is why those rows are
 * corroborated and why the writer stays strictly inside them rather than at
 * them.
 *
 * ## The floor is 1.13, and it is not the same floor as `.litematic`
 *
 * `setblock <pos> <block>` is what 1.13 gave and every release since has kept.
 * The bracketed block-state syntax is older -- 1.11 added it -- but flattened
 * ids are not, and `birch_stairs[facing=south]` means nothing to 1.12. The
 * litematic floor is a release later, at 1.13.2, because Litematica's own
 * reader converts anything below DataVersion 1631. Two formats, two answers,
 * and the difference is the reason both are written down.
 *
 * The mode word is deliberately absent from both forms. Omitted means
 * `replace`, which is what a schematic wants, and it is the one spelling every
 * release from 1.13 accepts: 1.21.5 added `strict` and relaxed `replace`, both
 * additions, neither of which the bare form has to know about.
 *
 * `.claude/skills/mc-commands` is how these are refreshed;
 * `resources/command_syntax.json` holds them with the wiki section each came
 * from.
 */

import type { McEra } from "./mc_versions.js";

export interface CommandForm {
  /** `setblock`, `fill`, or `block-argument` for the shared block spelling. */
  readonly command: string;
  /** The form this app writes. */
  readonly syntax: string;
  /** The oldest release that accepts it. */
  readonly since: string;
  /** That release's DataVersion, which is what a document actually carries. */
  readonly sinceDataVersion: number;
  readonly note: string;
}

export interface CommandLimit {
  /** The game rule's current name. */
  readonly name: string;
  /** What it was called before the 25w44a snake_case rename, or `null`. */
  readonly formerName: string | null;
  readonly renamedIn: string | null;
  readonly value: number;
  readonly applies: string;
  readonly note: string;
}

export const COMMAND_FORMS: readonly CommandForm[] = [
  // <<< generated by scripts/gen-command-syntax.mjs -- do not edit by hand
  { command: "setblock", syntax: "setblock <pos> <block>", since: "1.13", sinceDataVersion: 1519, note: "The mode word is left off on purpose: omitted means `replace`, which is what a schematic wants, and it is the one spelling every release from 1.13 accepts. 1.21.5 added `strict` as a further option without touching this form." },
  { command: "fill", syntax: "fill <from> <to> <block>", since: "1.13", sinceDataVersion: 1519, note: "Same reasoning as setblock. 1.21.5 made `replace` non-terminal and added `strict`; both are relaxations, so the bare form kept working." },
  { command: "block-argument", syntax: "<namespace:id>[state=value,...]{nbt}", since: "1.13", sinceDataVersion: 1519, note: "The namespace may be left off and defaults to `minecraft:`. Flattened ids arrived with 1.13, which is what makes that the floor rather than 1.11, when the bracket syntax itself was added." },
  // >>> end generated forms
];

export const COMMAND_LIMITS: readonly CommandLimit[] = [
  // <<< generated limits by scripts/gen-command-syntax.mjs -- do not edit by hand
  { name: "max_command_sequence_length", formerName: "maxCommandChainLength", renamedIn: "1.21.11", value: 65536, applies: "commands run inside one function", note: "Commands past it are ignored, with no error. This is why a large build is split across files with a dispatcher rather than written as one." },
  { name: "max_block_modifications", formerName: "commandModificationBlockLimit", renamedIn: "1.21.11", value: 32768, applies: "blocks changed by one /fill, /clone or /fillbiome", note: "A fill past it places nothing and says nothing useful, so no box this app writes may exceed it." },
  // >>> end generated limits
];

/** The oldest Minecraft release a written `.mcfunction` is runnable on. */
export const MCFUNCTION_MIN_DATA_VERSION = 1519;

/** How a human says it. Beside the number so a refusal can name the release. */
export const MCFUNCTION_MIN_LABEL = "1.13";

/**
 * Whether a version can be written as commands at all.
 *
 * `litematicCanCarry`'s sibling, and it answers the opposite way about
 * `null`: a litematic **must** stamp a `MinecraftDataVersion` and has nothing
 * honest to put there, while a `.mcfunction` carries no version tag of any
 * kind. An absent number is therefore not a claim this container has to
 * make, and refusing it would refuse every conversion that named no version.
 *
 * The era is asked as well as the number, and it is the half that does the
 * work: 1.8.8 and 1.8.9 genuinely have no DataVersion, so a number-only rule
 * would let the two oldest releases in the table through as though they had
 * said nothing. The floor is stated beside it rather than left implied --
 * the flat era happens to begin at exactly this release today, and
 * `tests/formats.ts` already states that this floor and Litematica's are
 * different releases, which is the reason not to write either as `era`.
 *
 * Until then this constant was reachable from nowhere but the tests: the
 * converter skipped its refusal for `.mcfunction` outright, so a 1.12.2
 * schematic came out as commands naming blocks that version has never had.
 */
export function mcfunctionCanCarry(era: McEra, dataVersion: number | null): boolean {
  if (era === "legacy") return false;
  return dataVersion === null || dataVersion >= MCFUNCTION_MIN_DATA_VERSION;
}

/**
 * Why commands cannot be written for a version, phrased for whoever picked
 * it. `refusalFor`'s shape, for `refusalFor`'s reason: the useful part is
 * which way to move, not that something is unavailable.
 */
export function mcfunctionRefusal(
  era: McEra,
  dataVersion: number | null,
  label: string,
): string | null {
  if (mcfunctionCanCarry(era, dataVersion)) return null;
  return (
    `A .mcfunction places blocks with setblock and fill, which name a block the ` +
    `flattened way -- minecraft:oak_stairs[facing=north]. That spelling arrived in ` +
    `${MCFUNCTION_MIN_LABEL}, so ${label} cannot be written as commands at all. Save ` +
    `it as MCEdit (.schematic) instead.`
  );
}

/**
 * A limit by name, or a thrown error.
 *
 * Thrown rather than defaulted, because the two callers below are module-level
 * constants: a silent fallback would mean a regenerated table that had dropped
 * a row still produced a working build, writing files against a number nobody
 * had checked.
 */
export function commandLimit(name: string): number {
  const found = COMMAND_LIMITS.find((limit) => limit.name === name);
  if (found === undefined) {
    throw new Error(
      `no limit named ${name} in command_syntax.ts -- regenerate it from ` +
        `resources/command_syntax.json`,
    );
  }
  return found.value;
}

/**
 * How many commands one function file may hold.
 *
 * Read out of the table rather than written here, so the skill refreshing the
 * data moves the writer with it and there is no second copy to drift.
 *
 * Note what this does *not* buy: a dispatcher calling twenty parts still runs
 * every one of their commands against one budget. Splitting makes each part
 * runnable on its own, and makes the output editable; it does not raise the
 * ceiling, and the writer says so in the dispatcher rather than letting the
 * game trim the build in silence.
 */
export const MAX_COMMANDS_PER_FUNCTION = commandLimit("max_command_sequence_length");

/** How many cells one `fill` may cover. */
export const MAX_FILL_VOLUME = commandLimit("max_block_modifications");
