/**
 * Which Minecraft versions this app can write, and what each one implies.
 *
 * In `shared/` rather than in main because three places need the same answer
 * and only one of them is main: the format picker offers containers, the
 * writers refuse the ones that cannot work, and the block inventory filters
 * what it shows. Same reason `openCodeModelRequiresKey` lives beside it — one
 * rule, mirrored by the UI and *enforced* by main.
 *
 * That third clause was a lie for a long time and is worth knowing about. The
 * inventory filtered air and the search box and nothing else, so a 1.12.2
 * schematic offered deepslate — placeable, drawable, and fatal at save time,
 * which is a long way from the click. It is true now, and `documentEra` below
 * is what made it possible to make true.
 *
 * ## Two eras, and the boundary is the Flattening
 *
 * | era      | versions      | blocks               | containers          |
 * |----------|---------------|----------------------|---------------------|
 * | `legacy` | 1.8.8 – 1.12.2| numeric `ID:DATA`    | MCEdit only         |
 * | `flat`   | 1.13 onward   | `namespace:id[state]`| Sponge v2/v3, MCEdit|
 *
 * **Sponge does not exist for the legacy era.** Its palette is a map of
 * flattened `namespace:id[state]` strings, and those strings did not exist
 * before 1.13. Offering it would write a file whose palette names blocks the
 * target game has never heard of — the classic error that looks like it worked.
 *
 * The internal representation stays flattened in both eras. Translation lives
 * at the edges and always has: `legacy_blocks.json` on the way in,
 * `writers.ts`'s `Materials: "Alpha"` branch on the way out. There is no second
 * document model here, and that is what makes supporting 1.8.8 sustainable
 * rather than a rewrite.
 *
 * ## On DataVersion, and why only 1.8.x carries none
 *
 * `DataVersion` is a tag inside a Sponge schematic. It did not exist as a
 * concept until snapshot 15w32a, which lands in 1.9 — so **1.8.8 and 1.8.9 are
 * the only rows in the table with `dataVersion: null`**, and that is the
 * *correct* value rather than a gap: `writers.ts` already omits the tag on
 * `null`. Every legacy row from 1.9 up carries a real number (1.12.2 is 1343),
 * because the version had one even though MCEdit has nowhere to put it. No
 * number is being guessed here, which matters — a wrong DataVersion produces a
 * file that looks right and misbehaves in game.
 *
 * This paragraph said "a legacy entry has `dataVersion: null`" until the
 * generated table was filled in underneath it, and then went on saying it. It
 * is the shape of stale documentation worth recognising: not wrong about a
 * design decision, wrong about *data*, and therefore invisible to everyone who
 * read the prose instead of the table. `documentEra` below depends on the
 * corrected sentence, so it is stated rather than assumed.
 *
 * Versions newer than the last row below are not missing by accident. Their
 * numbers have to be looked up and corroborated rather than remembered, which
 * is what `.claude/skills/mc-versions` is for.
 */

import type { SchematicFormat } from "./schematic.js";
import { LITEMATIC_MIN_LABEL, litematicCanCarry } from "./litematica_versions.js";

export type McEra = "legacy" | "flat";

export interface McVersionInfo {
  /** `mcschematic.Version` enum member name, e.g. `JE_1_20_4`. */
  readonly name: string;
  /** How a human says it. */
  readonly label: string;
  readonly era: McEra;
  /**
   * Minecraft's own `DataVersion`, or `null` when the version predates the tag
   * or is only ever written to a container that does not carry one.
   */
  readonly dataVersion: number | null;
}

/**
 * Newest first, which is the order the dropdown wants and the order
 * `mcschematic.Version` yields.
 *
 * Every row carries its real `DataVersion` except 1.8.8 and 1.8.9, which
 * predate the tag. See the note above: the legacy rows genuinely have numbers,
 * and the sentence that used to stand here said they did not.
 */
export const MC_VERSIONS: readonly McVersionInfo[] = [
  // <<< generated by scripts/gen-mc-versions.mjs -- do not edit by hand
  { name: "JE_26_2", label: "26.2", era: "flat", dataVersion: 4903 },
  { name: "JE_26_1", label: "26.1", era: "flat", dataVersion: 4786 },
  { name: "JE_1_21_11", label: "1.21.11", era: "flat", dataVersion: 4671 },
  { name: "JE_1_21_10", label: "1.21.10", era: "flat", dataVersion: 4556 },
  { name: "JE_1_21_9", label: "1.21.9", era: "flat", dataVersion: 4554 },
  { name: "JE_1_21_8", label: "1.21.8", era: "flat", dataVersion: 4440 },
  { name: "JE_1_21_7", label: "1.21.7", era: "flat", dataVersion: 4438 },
  { name: "JE_1_21_6", label: "1.21.6", era: "flat", dataVersion: 4435 },
  { name: "JE_1_21_5", label: "1.21.5", era: "flat", dataVersion: 4325 },
  { name: "JE_1_21_4", label: "1.21.4", era: "flat", dataVersion: 4189 },
  { name: "JE_1_21_3", label: "1.21.3", era: "flat", dataVersion: 4082 },
  { name: "JE_1_21_1", label: "1.21.1", era: "flat", dataVersion: 3955 },
  { name: "JE_1_21", label: "1.21", era: "flat", dataVersion: 3953 },
  { name: "JE_1_20_6", label: "1.20.6", era: "flat", dataVersion: 3839 },
  { name: "JE_1_20_5", label: "1.20.5", era: "flat", dataVersion: 3837 },
  { name: "JE_1_20_4", label: "1.20.4", era: "flat", dataVersion: 3700 },
  { name: "JE_1_20_2", label: "1.20.2", era: "flat", dataVersion: 3578 },
  { name: "JE_1_20_1", label: "1.20.1", era: "flat", dataVersion: 3465 },
  { name: "JE_1_20", label: "1.20", era: "flat", dataVersion: 3463 },
  { name: "JE_1_19_4", label: "1.19.4", era: "flat", dataVersion: 3337 },
  { name: "JE_1_19_3", label: "1.19.3", era: "flat", dataVersion: 3218 },
  { name: "JE_1_19_2", label: "1.19.2", era: "flat", dataVersion: 3120 },
  { name: "JE_1_19", label: "1.19", era: "flat", dataVersion: 3105 },
  { name: "JE_1_18_2", label: "1.18.2", era: "flat", dataVersion: 2975 },
  { name: "JE_1_18_1", label: "1.18.1", era: "flat", dataVersion: 2865 },
  { name: "JE_1_18", label: "1.18", era: "flat", dataVersion: 2860 },
  { name: "JE_1_17_1", label: "1.17.1", era: "flat", dataVersion: 2730 },
  { name: "JE_1_17", label: "1.17", era: "flat", dataVersion: 2724 },
  { name: "JE_1_16_5", label: "1.16.5", era: "flat", dataVersion: 2586 },
  { name: "JE_1_16_4", label: "1.16.4", era: "flat", dataVersion: 2584 },
  { name: "JE_1_16_2", label: "1.16.2", era: "flat", dataVersion: 2578 },
  { name: "JE_1_16_1", label: "1.16.1", era: "flat", dataVersion: 2567 },
  { name: "JE_1_16", label: "1.16", era: "flat", dataVersion: 2566 },
  { name: "JE_1_15_2", label: "1.15.2", era: "flat", dataVersion: 2230 },
  { name: "JE_1_15", label: "1.15", era: "flat", dataVersion: 2225 },
  { name: "JE_1_14_4", label: "1.14.4", era: "flat", dataVersion: 1976 },
  { name: "JE_1_14", label: "1.14", era: "flat", dataVersion: 1952 },
  { name: "JE_1_13_2", label: "1.13.2", era: "flat", dataVersion: 1631 },
  { name: "JE_1_13", label: "1.13", era: "flat", dataVersion: 1519 },
  { name: "JE_1_12_2", label: "1.12.2", era: "legacy", dataVersion: 1343 },
  { name: "JE_1_12_1", label: "1.12.1", era: "legacy", dataVersion: 1241 },
  { name: "JE_1_12", label: "1.12", era: "legacy", dataVersion: 1139 },
  { name: "JE_1_11_2", label: "1.11.2", era: "legacy", dataVersion: 922 },
  { name: "JE_1_11", label: "1.11", era: "legacy", dataVersion: 819 },
  { name: "JE_1_10_2", label: "1.10.2", era: "legacy", dataVersion: 512 },
  { name: "JE_1_10", label: "1.10", era: "legacy", dataVersion: 510 },
  { name: "JE_1_9_4", label: "1.9.4", era: "legacy", dataVersion: 184 },
  { name: "JE_1_9", label: "1.9", era: "legacy", dataVersion: 169 },
  { name: "JE_1_8_9", label: "1.8.9", era: "legacy", dataVersion: null },
  { name: "JE_1_8_8", label: "1.8.8", era: "legacy", dataVersion: null },
  // >>> end generated
];

const BY_NAME = new Map(MC_VERSIONS.map((entry) => [entry.name, entry]));

/**
 * The same rows under the spelling a person uses.
 *
 * `26.2` is what somebody asks for and `JE_26_2` is what the table calls it,
 * and until this existed only the second one worked -- see
 * `resolveVersionName` for what that cost.
 */
const BY_LABEL = new Map(MC_VERSIONS.map((entry) => [entry.label, entry]));

export function mcVersion(name: string): McVersionInfo | undefined {
  return BY_NAME.get(name);
}

/**
 * The canonical name of a version, given the name **or** the label.
 * `null` for anything this build does not know.
 *
 * ## Why a second spelling
 *
 * The name is what settings round-trip and what every table is keyed on, so
 * it stays the canonical form. But `JE_26_2` is a spelling nobody says out
 * loud: asked for 26.2, a model sends `"26.2"`, and before this that string
 * reached `dataVersionOf`, missed, and came back `null` -- which is
 * indistinguishable from 1.8.8's genuine absence of a DataVersion and from no
 * version having been asked for at all. The document was created with no
 * version tag and **nothing was raised**.
 *
 * ## Why `null` rather than a guess
 *
 * Two spellings is the limit. `1.20` does not resolve to `JE_1_20_4`, and a
 * near-miss is not repaired: this is the function every caller checks before
 * refusing by name, so a guess here would put the silence back one level
 * down. `UnknownVersionError` already has the sentence for the refusal.
 *
 * Every caller resolves **first** and passes the canonical name onwards, so
 * there is one place that knows about labels and everything downstream keeps
 * seeing exactly what it saw before.
 */
export function resolveVersionName(input: string): string | null {
  const asked = input.trim();
  if (asked === "") return null;
  return (BY_NAME.get(asked) ?? BY_LABEL.get(asked))?.name ?? null;
}

/**
 * Which era a version belongs to.
 *
 * Unknown names are treated as `flat`, which is the permissive answer and the
 * right one: a settings file written by a newer build names a version this one
 * has never heard of, and refusing every container for it would leave the user
 * unable to save at all. The `flat` guess costs nothing when it is wrong,
 * because MCEdit is offered in both eras.
 */
export function eraOf(name: string): McEra {
  return BY_NAME.get(name)?.era ?? "flat";
}

/**
 * Which containers a version can actually be written to, best first.
 *
 * The whole point of this module. MCEdit is in both lists because it works in
 * both eras — lossily above 1.13, which `writers.ts` already reports through
 * `degraded`, and natively below it.
 *
 * **Litematica needs one release more than the era does.** The era rule is
 * about the Flattening and is right about Sponge: 1.13 has flattened block
 * names, so a Sponge palette can be written for it. Litematica's own reader
 * converts the palette of anything below DataVersion 1631, so a `.litematic`
 * claiming 1.13 or 1.13.1 comes back as the wrong blocks rather than as an
 * error. `litematicCanCarry` holds that line; `litematica_versions.ts` holds
 * the reasoning.
 *
 * An unknown version name gets `flat` from `eraOf` and still does not get
 * litematic, because `dataVersionOf` has no number for it — and a container
 * that must stamp a `MinecraftDataVersion` cannot be offered for a version
 * whose number this build has never heard of. Sponge is still there, so
 * nobody is left unable to save.
 */
export function formatsFor(name: string): readonly SchematicFormat[] {
  if (eraOf(name) === "legacy") return ["mcedit"];
  return litematicCanCarry(dataVersionOf(name))
    ? ["sponge3", "litematic", "sponge2", "mcedit"]
    : ["sponge3", "sponge2", "mcedit"];
}

/** Whether a container can carry a version at all. */
export function formatSupportsVersion(format: SchematicFormat, name: string): boolean {
  return formatsFor(name).includes(format);
}

/**
 * Why a container was refused, phrased for the person who picked it.
 *
 * A sentence rather than a boolean because the reason is the useful part: "not
 * available" invites the user to look for a setting that would enable it, and
 * there is none — the format genuinely cannot represent that version.
 */
export function refusalFor(format: SchematicFormat, name: string): string | null {
  /*
   * Named first, because the sentence below interpolates the label and an
   * empty name interpolates nothing: the refusal came out reading "a
   * .litematic claiming  would open in the mod as the wrong blocks", which
   * is a message with a hole where the fact should be. Reachable from any
   * caller that treats an absent version as a version.
   */
  if (name.trim() === "") {
    return (
      `No Minecraft version was given, and a container has to know one to be written. ` +
      `Name one, such as ${MC_VERSIONS[0].name} (${MC_VERSIONS[0].label}).`
    );
  }
  if (formatSupportsVersion(format, name)) return null;
  const label = mcVersion(name)?.label ?? name;
  /*
   * Two refusals, because there are two reasons and only one of them is the
   * Flattening. Sending someone who picked Litematica for 1.13 to read about
   * flattened block names would be true and useless: 1.13 *has* those.
   */
  if (format === "litematic") {
    return (
      `Litematica converts the palette of any schematic older than ${LITEMATIC_MIN_LABEL}, so a ` +
      `.litematic claiming ${label} would open in the mod as the wrong blocks rather than as an ` +
      `error. Write ${LITEMATIC_MIN_LABEL} or newer, or save it as Sponge.`
    );
  }
  return (
    `Sponge schematics store blocks as flattened names like minecraft:oak_stairs[facing=north], ` +
    `which did not exist before 1.13. ${label} is older than that, so it can only be written as ` +
    `MCEdit (.schematic).`
  );
}

/** Every version name, newest first — what the dropdown shows. */
export const MC_VERSION_NAMES: readonly string[] = MC_VERSIONS.map((entry) => entry.name);

/**
 * Which versions each container holds, as one sentence, built from the table.
 *
 * For the tool schemas an MCP client reads. Every number in it is looked up
 * rather than typed: `oldestFor` asks `versionsFor`, which asks the era rule
 * and the two floors, so a release added to `mc_versions.json` moves this
 * sentence with it and the MCP surface needs no edit at all.
 *
 * That is the whole point rather than tidiness. The bug this was written for
 * was a hand-typed `JE_1_20_4` in a tool description going stale, and an
 * `enum` of fifty names plus a sentence saying "39 versions" would be the
 * same mistake four tools wide.
 */
export function versionRangesSentence(): string {
  const oldestFor = (format: SchematicFormat): string => {
    const offered = versionsFor(format);
    const last = offered[offered.length - 1] ?? "";
    return mcVersion(last)?.label ?? last;
  };
  const lastLegacy = MC_VERSIONS.find((entry) => entry.era === "legacy")?.label ?? "";
  return (
    `sponge3 and sponge2 need ${oldestFor("sponge3")} or newer; litematic needs ` +
    `${oldestFor("litematic")} or newer; mcedit takes any version, natively up to ` +
    `${lastLegacy} and lossily above it.`
  );
}

/** Versions that can be written to a given container, newest first. */
export function versionsFor(format: SchematicFormat): readonly string[] {
  return MC_VERSIONS.filter((entry) => formatSupportsVersion(format, entry.name)).map(
    (entry) => entry.name,
  );
}

/** The `DataVersion` tag a version wants, or `null` for none. */
export function dataVersionOf(name: string): number | null {
  return BY_NAME.get(name)?.dataVersion ?? null;
}

/**
 * The version a `DataVersion` came from, or `null`.
 *
 * Only ever used to preselect a dropdown, so a document with no tag or an
 * unrecognised one gets `null` and the caller falls back to a default rather
 * than to a wrong-but-plausible row.
 */
export function versionNameOf(dataVersion: number | null): string | null {
  if (dataVersion === null) return null;
  return MC_VERSIONS.find((entry) => entry.dataVersion === dataVersion)?.name ?? null;
}

/**
 * Which era an *open document* belongs to.
 *
 * Not the same question as `eraOf`, and the difference is the whole reason this
 * exists. `eraOf` takes a version *name* and answers `flat` for anything it does
 * not recognise, which is the right permissive answer for a settings string
 * written by a newer build. Asked about a document it is the wrong answer, and
 * it was the one every caller got: a `.schematic` loaded from disk arrives with
 * `dataVersion: null` — MCEdit has no such tag — so `versionNameOf` gives
 * `null`, `eraOf("")` gives `flat`, and **every legacy schematic in the app
 * presented itself as 1.13+**. The inventory offered it deepslate, the editor
 * let it place deepslate, and the failure surfaced at save time as
 * `UnrepresentableBlocksError`, which is a long way from the click that caused
 * it.
 *
 * A missing tag is therefore read from the *container*, which is the only other
 * fact in evidence and is sufficient: MCEdit is the one container the legacy era
 * can be written to (`formatsFor` above), and the legacy era is the only one in
 * which a version can legitimately have no DataVersion at all — 1.8.8 and 1.8.9,
 * and nothing else. So a document with no tag in an MCEdit container is legacy,
 * and a document with no tag in any other container is a Sponge file that
 * omitted the optional tag, or a `.mcfunction`, both of which are flat.
 *
 * It is *not* keyed on the format alone, which is the tempting one-liner and is
 * wrong in the direction that costs something: saving a modern build as MCEdit
 * is a legitimate, lossy thing to do — it is what `degraded` reports on — and
 * that document keeps its own DataVersion. Reading it as legacy would refuse
 * every block in it.
 */
export function documentEra(format: SchematicFormat, dataVersion: number | null): McEra {
  if (dataVersion !== null) return eraOf(versionNameOf(dataVersion) ?? "");
  return format === "mcedit" ? "legacy" : "flat";
}

/**
 * What a legacy document is assumed to be when its file names no version.
 *
 * The newest of the era, and deliberately so: `legacy_blocks.json` is the 1.12
 * registry, so it is the version this app can actually check a block against.
 * Guessing older would refuse blocks the table says are fine.
 *
 * It is a *display and preselection* default, never written to a file on its
 * own — the version modal is where somebody says which one it really is, and
 * that is the moment the guess stops being a guess.
 */
export const DEFAULT_LEGACY_VERSION = "JE_1_12_2";

/**
 * The version name to show for an open document, or `null` when it named none.
 *
 * `versionNameOf` alone is not enough for the same reason `documentEra` exists:
 * a loaded legacy file has no number, so it would come back `null` and every
 * caller would fall through to the *global* default — which is a flat version,
 * displayed against a legacy document. Falling back within the document's own
 * era is the smaller wrong, and it is what the picker needs to preselect.
 *
 * Still `null` for a flat document with no tag, because there the absence is
 * real information: a Sponge file may omit `DataVersion`, and inventing one
 * would put a number into a file that deliberately carried none.
 */
export function documentVersionName(
  format: SchematicFormat,
  dataVersion: number | null,
): string | null {
  const exact = versionNameOf(dataVersion);
  if (exact !== null) return exact;
  return documentEra(format, dataVersion) === "legacy" ? DEFAULT_LEGACY_VERSION : null;
}
